version: "3"

silent: false

tasks:
    default:
        deps:
            - build

    docs:
        cmds:
            - npx typedoc
              --excludeInternal
              --excludePrivate
              --excludeProtected
              --out docs
              --validation.invalidLink
              --entryPoints src/index.js src/browser.js src/native.js

    install:
        cmds:
            - pnpm i

    build:
        deps:
            - install
        cmds:
            - task: format
            - task: lint
            - npx babel src -d lib --out-file-extension .cjs
            - npx yalc publish

    clean:
        cmds:
            - rm -rf node_modules

    format:
        cmds:
            - npx prettier src "test/unit/*.js" "*.json" "src/*.js" --write

    lint:
        deps:
            - "lint:types"
            - "lint:dpdm"
            - "lint:format"
            - "lint:js"

    "lint:types":
        cmds:
            - npx tsc

    "lint:dpdm":
        cmds:
            - npx dpdm src/index.js --circular true --tree false --warning false

    "lint:format":
        cmds:
            - npx prettier src "test/unit/*.js" "*.json" "src/*.js" --check

    "lint:js":
        cmds:
            - npx eslint --fix "src/**/*.js" "test/unit/**/*.js"

    "test:release":
        cmds:
            - task: test:unit

    test:
        deps:
            - "test:unit"

    "test:unit":
        deps:
            - "test:unit:node"
            - "test:unit:browser"

    "test:unit:node":
        cmds:
            - npx vitest --config=test/vitest-node.config.ts

    "test:unit:codecov":
        cmds:
            - npx vitest --coverage --config=test/vitest-node.config.ts

    "test:unit:browser":
        cmds:
            - npx vitest --config=test/vitest-browser.config.ts

    update:
        cmds:
            - task: build

    pack:
        preconditions:
            - '! grep ''".*": "link:.*"'' package.json'
        deps:
            - "build"
        cmds:
            - pnpm pack --out {{.CLI_ARGS}}
            - ls -lh {{.CLI_ARGS}}

    publish:
        cmds:
            - npm publish {{.TARBALL}} {{.CLI_ARGS}}
