version: "3"

silent: false

includes:
    examples:
        taskfile: ./examples/Taskfile.yml
        dir: ./examples

    common_js_test:
        taskfile: ./common_js_test/Taskfile.yml
        dir: ./common_js_test

    simple_rest_signature_provider:
        taskfile: ./examples/simple_rest_signature_provider/Taskfile.yml
        dir: ./examples/simple_rest_signature_provider

    proto:
        taskfile: ./packages/proto/Taskfile.yml
        dir: ./packages/proto

    cryptography:
        taskfile: ./packages/cryptography/Taskfile.yml
        dir: ./packages/cryptography

tasks:
    default:
        deps:
            - build

    "run:examples":
        cmds:
            - task: "examples:run-examples"

    docs:
        cmds:
            - npx typedoc
              --excludeInternal
              --excludePrivate
              --excludeProtected
              --out docs
              --validation.invalidLink
              --entryPoints src/index.js src/browser.js src/native.js

    "yalc:install":
        cmds:
            - npm install -g yalc

    "yalc:add":
        cmds:
            - npx yalc add @hiero-ledger/proto
            - npx yalc add @hiero-ledger/cryptography

    "yalc:remove":
        cmds:
            - npx yalc remove @hiero-ledger/proto
            - npx yalc remove @hiero-ledger/cryptography

    install:
        deps:
            - "yalc:install"
            - "proto:build"
            - "cryptography:build"
        cmds:
            - task: "yalc:add"
            - pnpm i --no-frozen-lockfile

    build:
        cmds:
            - task: build:prep
            - task: build:compile

    "build:prep":
        cmds:
            - task: install
            - task: format
            - task: lint
            - node ./scripts/generate-request-and-status-files.js

    "build:compile":
        cmds:
            - npx babel src -d lib --out-file-extension .cjs
            - npx rollup -c
            - npx yalc publish

    clean:
        deps:
            - "examples:clean"
            - "cryptography:clean"
            - "proto:clean"
            - "simple_rest_signature_provider:clean"
            - "common_js_test:clean"
        cmds:
            - rm -rf node_modules .yalc

    format:
        cmds:
            - npx prettier src "test/unit/*.js" "test/integration/*.js" "*.json" "src/*.js" "scripts/*.js" --write

    lint:
        deps:
            - "lint:types"
            - "lint:dpdm"
            - "lint:format"
            - "lint:js"

    "lint:types":
        cmds:
            - npx tsc

    "lint:dpdm":
        cmds:
            # It's really annoying seeing [X/X] Analyze done. If a circular dep is found remove `2>&1`
            - npx dpdm src/index.js --circular true --tree false --warning false

    "lint:format":
        cmds:
            - npx prettier src "test/unit/*.js" "test/integration/*.js" "*.json" "src/*.js" --check

    "lint:js":
        cmds:
            - npx eslint --fix "src/**/*.js" "test/integration/**/*.js" "test/unit/**/*.js"

    "test:release":
        cmds:
            - task: build
            - task: test:unit
            - task: examples:build
            - task: simple_rest_signature_provider:build
            - task: common_js_test:build

    test:
        deps:
            - "test:unit"
            - "test:integration"

    "test:unit":
        deps:
            - "test:unit:node"
            - "test:unit:browser"

    "test:unit:node":
        cmds:
            - npx vitest --config=test/vitest-node.config.ts

    "test:unit:codecov":
        cmds:
            - npx vitest --coverage --config=test/vitest-node.config.ts

    "test:unit:browser":
        cmds:
            - npx vitest --config=test/vitest-browser.config.ts

    "test:integration":
        deps:
            - "test:integration:node"
            - "test:integration:browser"

    "test:integration:node":
        cmds:
            - npx vitest --config=test/vitest-node-integration.config.ts

    "test:integration:browser":
        cmds:
            - npx vitest --config=test/vitest-browser-integration.config.ts

    "test:integration:codecov":
        cmds:
            - npx vitest --coverage --config=test/vitest-node-integration.config.ts
            - npx vitest --coverage --config=test/vitest-browser-integration.config.ts

    "test:integration:dual-mode":
        cmds:
            - npx vitest --poolOptions.threads.singleThread --config=test/vitest-node-integration-dual-mode.config.ts
            - npx vitest --poolOptions.threads.singleThread --config=test/vitest-browser-integration-dual-mode.config.ts

    "update:proto":
        deps:
            - "proto:update"
        cmds:
            - npx yalc add @hiero-ledger/proto
            # Remove proto so on `task build` we fix the link
            - rm -rf ./node_modules/@hiero-ledger/proto

    "update:addressbooks":
        cmds:
            - node ./scripts/update-address-books.js

    update:
        cmds:
            - task: update:addressbooks
            - task: update:proto
            - task: build

    pack:
        preconditions:
            - "! grep '\".*\": \"\\(link\\|file\\):.*\"' package.json"
        deps:
            - "build"
        cmds:
            - task: "yalc:remove"
            - pnpm pack --out {{.PACKAGE_NAME}}

    "publish":
        cmds:
            - pnpm publish {{.CLI_ARGS}}
