version: "3"

tasks:
    check-node:
        desc: "Check if Node.js is installed and meets the version requirement"
        silent: true
        cmds:
            - echo "Checking Node.js version..."
            - |
                if ! command -v node &> /dev/null || [ "$(node -v | cut -d'.' -f1)" -lt "v20" ]; then
                  echo "Node.js v20 or higher is required. Please install it."
                  exit 1
                fi

    check-npm:
        desc: "Check if npm is installed and meets the version requirement"
        silent: true
        cmds:
            - echo "Checking npm version..."
            - |
                if ! command -v npm &> /dev/null || [ "$(npm -v | cut -d'.' -f1)" -lt "10" ]; then
                  echo "NPM v10 or higher is required. Please install it."
                  exit 1
                fi

    install-hedera-local:
        desc: "Install Hedera Local Node CLI tool if not installed"
        silent: true
        cmds:
            - echo "Checking for Hedera Local Node CLI..."
            - |
                if ! command -v hedera &> /dev/null; then
                  echo "Hedera Local Node CLI not found, installing..."
                  npm install @hashgraph/hedera-local -g
                else
                  echo "Hedera Local Node CLI is already installed."
                fi

    start-local-node:
        desc: "Start the local Hedera network"
        silent: true
        deps: [check-node, check-npm, install-hedera-local]
        cmds:
            - echo "Starting local Hedera network..."
            - hedera start

    pull-hiero-tck-client:
        desc: "Pull the Docker image for hiero-tck-client"
        cmds:
            - echo "Pulling Docker image for hiero-tck-client..."
            - docker pull ivaylogarnev/hiero-tck-client

    build-tck-js-server:
        desc: "Build the Docker image for tck-js-server"
        deps: [pull-hiero-tck-client]
        silent: true
        cmds:
            - echo "Building Docker image for tck-js-server..."
            - docker build -t tck-js-server .

    run-specific-test:
        desc: "Run all services with a specific test"
        silent: true
        deps: [start-local-node, build-tck-js-server]
        vars:
            TEST: '{{.TEST | default "ALL"}}'
            NETWORK: '{{.NETWORK | default "local"}}'
            OPERATOR_ACCOUNT_ID: "{{.OPERATOR_ACCOUNT_ID}}"
            OPERATOR_ACCOUNT_PRIVATE_KEY: "{{.OPERATOR_ACCOUNT_PRIVATE_KEY}}"
            MIRROR_NODE_REST_URL: "{{.MIRROR_NODE_REST_URL}}"
            MIRROR_NODE_REST_JAVA_URL: "{{.MIRROR_NODE_REST_JAVA_URL}}"
        cmds:
            - |
                export TEST={{.TEST | default "ALL"}}
                export NETWORK={{.NETWORK | default "local"}}
                export OPERATOR_ACCOUNT_ID={{.OPERATOR_ACCOUNT_ID}}
                export OPERATOR_ACCOUNT_PRIVATE_KEY="{{.OPERATOR_ACCOUNT_PRIVATE_KEY}}"
                export MIRROR_NODE_REST_URL="{{.MIRROR_NODE_REST_URL}}"
                export MIRROR_NODE_REST_JAVA_URL="{{.MIRROR_NODE_REST_JAVA_URL}}"
                if [ "$NETWORK" = "testnet" ]; then
                    if [ -z "$OPERATOR_ACCOUNT_ID" ] || [ -z "$OPERATOR_ACCOUNT_PRIVATE_KEY" ]; then
                        echo "Error: OPERATOR_ACCOUNT_ID and OPERATOR_ACCOUNT_PRIVATE_KEY must be provided for testnet."
                        exit 1
                    fi
                fi
                docker compose up

    start-all-tests:
        desc: "Start Docker Compose services"
        silent: true
        deps: [start-local-node, build-tck-js-server]
        vars:
            NETWORK: '{{.NETWORK | default "local"}}'
            OPERATOR_ACCOUNT_ID: "{{.OPERATOR_ACCOUNT_ID}}"
            OPERATOR_ACCOUNT_PRIVATE_KEY: "{{.OPERATOR_ACCOUNT_PRIVATE_KEY}}"
            MIRROR_NODE_REST_URL: "{{.MIRROR_NODE_REST_URL}}"
            MIRROR_NODE_REST_JAVA_URL: "{{.MIRROR_NODE_REST_JAVA_URL}}"
        cmds:
            - echo "Starting Docker Compose services..."
            - |
                export TEST={{.TEST | default "ALL"}}
                export NETWORK={{.NETWORK | default "local"}}
                export OPERATOR_ACCOUNT_ID={{.OPERATOR_ACCOUNT_ID}} 
                export OPERATOR_ACCOUNT_PRIVATE_KEY="{{.OPERATOR_ACCOUNT_PRIVATE_KEY}}"
                export MIRROR_NODE_REST_URL="{{.MIRROR_NODE_REST_URL}}"
                export MIRROR_NODE_REST_JAVA_URL="{{.MIRROR_NODE_REST_JAVA_URL}}"
                if [ "$NETWORK" = "testnet" ]; then
                    if [ -z "$OPERATOR_ACCOUNT_ID" ] || [ -z "$OPERATOR_ACCOUNT_PRIVATE_KEY" ]; then
                        echo "Error: OPERATOR_ACCOUNT_ID and OPERATOR_ACCOUNT_PRIVATE_KEY must be provided for testnet."
                        exit 1
                    fi
                fi
                docker compose up

    default:
        desc: "Start local node and Docker Compose"
        silent: true
        deps: [start-all-tests]

    tag-previous-version:
        desc: Tags the current 'latest' Docker images (both regular and AMD64) with a specific version number
        silent: true
        vars:
            VERSION: "{{.VERSION}}"
        cmds:
            - echo "Tagging both regular and AMD64 images with version {{.VERSION}}"
            # Regular image
            - echo "Processing regular image..."
            - docker pull ivaylogarnev/js-tck-server:latest
            - docker tag ivaylogarnev/js-tck-server:latest ivaylogarnev/js-tck-server:{{.VERSION}}
            - docker push ivaylogarnev/js-tck-server:{{.VERSION}}
            # AMD64 image
            - echo "Processing AMD64 image..."
            - docker pull ivaylogarnev/js-tck-server-amd:latest
            - docker tag ivaylogarnev/js-tck-server-amd:latest ivaylogarnev/js-tck-server-amd:{{.VERSION}}
            - docker push ivaylogarnev/js-tck-server-amd:{{.VERSION}}
        preconditions:
            - sh: test -n "{{.VERSION}}"
              msg: "VERSION parameter is required. Usage: task tag-previous-version VERSION=x.y.z"

    release-js-tck-server:
        desc: Builds and pushes both regular and AMD64 Docker images
        silent: true
        cmds:
            # Regular image
            - echo "Building and pushing regular Docker image"
            - docker build -t ivaylogarnev/js-tck-server:latest -f Dockerfile .
            - docker push ivaylogarnev/js-tck-server:latest
            # AMD64 image
            - echo "Building and pushing AMD64 Docker image"
            - docker build --platform linux/amd64 -t ivaylogarnev/js-tck-server-amd:latest -f Dockerfile .
            - docker push ivaylogarnev/js-tck-server-amd:latest
