import { defineConfig } from "vitest/config";

/** @type {import("vitest").UserConfig} */
export default defineConfig({
    test: {
        watch: false,
        globals: true,
        environment: "node",
        pool: "threads",
        isolate: false,
        include: ["test/unit/**/*.js"],
        exclude: [
            "test/unit/keystore.js",
            "test/unit/primitive/aes.browser.js",
        ],
        testTimeout: 8000,
        coverage: {
            provider: "v8",
            include: ["src/**/*.js"],
            exclude: [
                "src/SignatureMapLegacy.js",
                "src/NodeAccountIdSignatureMapLegacy.js",
                "src/Transaction.js",
                "src/TopicCreateTransaction.js",
                "src/TopicMessageSubmitTransaction.js",
                "src/TopicId.js",
                "src/TokenUpdateTransaction.js",
                "src/TokenId.js",
                "src/TokenNftInfoQuery.js",
                "src/TokenNftsUpdateTransaction.js",
                "src/FreezeTransaction.js",
                "src/ScheduleId.js",
                "src/FileId.js",
                "src/StorageChange.js",
                "src/DelegateContractId.js",
                "src/ContractUpdateTransaction.js",
                "src/ContractStateChange.js",
                "src/ContractFunctionResult.js",
                "src/ContractId.js",
                "src/ContractCreateTransaction.js",
                "src/NodeClient.js",
                "src/ManagedNetwork.js",
                "src/Client.js",
                "src/TransferTransaction.js",
                "src/AccountUpdateTransaction.js",
                "src/LiveHashQuery.js",
                "src/LiveHashAddTransaction.js",
                "src/LiveHashDeleteTransaction.js",
                "src/Wallet.js",
                "src/AccountInfo.js",
                "src/AccountAllowanceApproveTransaction.js",
                "src/AccountId.js",
                "src/AccountCreateTransaction.js",
                "src/AccountAllowanceAdjustTransaction.js",
            ],
            reporter: ["text-summary", "lcov"],
            reportsDirectory: "./coverage/node",
        },
    },
});
