name: Common JS
on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test-integration-node:
    name: Integration Tests on Node ${{ matrix.node }}
    runs-on: hiero-client-sdk-linux-large
    strategy:
      matrix:
        node: [ "22", "24" ]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: Install Task
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          version: 3.35.1

      - name: Install PNPM
        uses: step-security/action-setup@7734f5522f614a4cf2820ad19aa26717c7abfd96 # v6.0.9
        with:
          version: 9.15.5

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Build @hiero-ledger/sdk
        run: task build

      - name: Install dependencies
        working-directory: common_js_test
        run: task install

      - name: Test
        working-directory: common_js_test
        run: task test
