# This workflow has been disabled from the GH Actions Server side (gh CLI or Github UI).
name: React Native
on:
  push:
    branches:
      - main
      - develop
      - release/*
      - build
  pull_request:
    branches:
      - main
      - develop
      - release/*

defaults:
    run:
        shell: bash

permissions:
  contents: read

jobs:
  android:
    name: Android
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: "zulu"
          java-version: "8"

      - name: Install Task
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          version: 3.35.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"

      - name: Install PNPM
        uses: step-security/action-setup@0ad50dc56a23060fa78b14cfcf0677c4e14b42bc # v5.0.0
        with:
          version: 9.15.5

      - name: Build @hiero-ledger/sdk
        run: task build

      - name: Install detox
        run: npm install -g detox-cli

      - name: Install React Native example deps
        run: pnpm install --filter react-native-example

      - name: AVD
        run: |
          brew install android-platform-tools
          pnpm install -g envinfo detox-cli && envinfo
          echo yes | $ANDROID_HOME/tools/bin/sdkmanager --channel=0 --verbose "system-images;android-28;default;x86_64"
          $ANDROID_HOME/tools/bin/avdmanager --verbose create avd --force --name "Nexus6P" --package "system-images;android-28;default;x86_64" --sdcard 200M --device 11
          adb start-server

      - name: Build
        working-directory: examples/react-native-example
        run: detox build --configuration android

      - name: Test
        working-directory: examples/react-native-example
        run: detox test --configuration android

  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: "zulu"
          java-version: "8"

      - name: Install Task
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          version: 3.7.0

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"

      - name: Install PNPM
        uses: step-security/action-setup@0ad50dc56a23060fa78b14cfcf0677c4e14b42bc # v5.0.0
        with:
          version: 9.15.5

      - name: Build @hiero-ledger/sdk
        run: task build

      - name: Install detox
        run: npm install -g detox-cli

      - name: Install React Native example deps
        run: pnpm install --filter react-native-example

      - name: Build
        working-directory: examples/react-native-example
        run: |
          brew tap wix/brew
          brew install applesimutils
          detox build --configuration ios

      - name: Test
        working-directory: examples/react-native-example
        run: detox test --configuration ios
