name: "Slack Merge Notification"
on:
    pull_request:
        types:
            - closed

env:
    js-sdk-channel-id: C0958RN2ZTR

defaults:
    run:
        shell: bash

permissions:
    contents: read
    pull-requests: read

jobs:
    notify-slack:
        name: Notify Slack
        if: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'codacy-production[bot]' && github.event.pull_request.user.login != 'lfdt-bot' && github.event.pull_request.user.login != 'codecov[bot]' }}
        runs-on: hiero-client-sdk-linux-medium
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
              with:
                  egress-policy: audit

            - name: Send Slack Notification
              uses: slackapi/slack-github-action@03ea5433c137af7c0495bc0cad1af10403fc800c # v3.0.2
              with:
                  method: chat.postMessage
                  token: ${{ secrets.SLACK_BOT_TOKEN }}
                  payload: |
                      {
                        "channel": "${{ env.js-sdk-channel-id }}",
                        "text": ":meow_merged: ${{ github.event.pull_request.head.ref }} has been merged into ${{ github.event.pull_request.base.ref }} by ${{ github.event.pull_request.merged_by.login }} — <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}>"
                      }
