name: 'Slack Release Notification'
on:
  release:
    types:
      - published

env:
  js-sdk-channel-id: C0958RN2ZTR

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  notify-slack:
    name: Notify Slack
    runs-on: hiero-client-sdk-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.js-sdk-channel-id }}",
              "text": ":js-release: New release published: ${{ github.event.release.tag_name }} — <${{ github.event.release.html_url }}|View release>"
            }
